### ISSUE TITLE
 Missing "alábontás" - inserted after offer

### ISSUE THREAD

**Issue by AbstractFlame** [AbstractFlame/receptes#54]
A nemzetköziből hiányzik az USA / Kanada alábontás. (Ha ezt esetleg később raktam volna be, akkor elnézést. A mellékletben már vannak ilyen receptek is.)

Akkor rakja majd bele az új adatbázisba Ő. NEM A MI DOLGUNK ÚGY HISZEM. De ennek ellenére úgy érzem meg kéne csinálni.

email: 9.

**Comment by samub** [comment]
kép is kéne hozzája, de nem találom, addig leszarom majd hivatkozz rá hogy nem küldött képet

**Comment by AbstractFlame** [comment]
Miért kell hozzá kép? Elvileg a program hiányzó képfájlok esetén is működik már.

**Comment by samub** [comment]
az jó, ha berakom a final db-be és azzal felülírom a testing DB-t ?

**Comment by AbstractFlame** [comment]
Email: Az sqLiteStudio segítségével mostantól el tudja végezni a kívánt módosításokat a csoportosításon, illetve a Dictionary-n is.
