### ISSUE TITLE
Beautiful heading missing

### ISSUE THREAD

**Issue by AbstractFlame** [AbstractFlame/receptes#56]
Hiányzik a teljes felső rész (adott nyelvi receptek számlálója + két figyelmeztetés + revízió). A revíziónak minden megnyitott ablak jobb felső sarkában láthatónak kell lennie.

email: 11.

**Comment by AbstractFlame** [comment]
Minden ablak jobb felső részébe kell a revision szám: 4.0

**Comment by samub** [comment]
Már "csak " a Count-ot kell beírni, megvan a kód csak értéket kell neki adni. Gyakorlatilag egy 
Count (*) where lang=actualLang féleség kéne de nem mertem megcsinalni :D
