### ISSUE TITLE
Missing "Full screeen preview" function... wtf???

### ISSUE THREAD

**Issue by AbstractFlame** [AbstractFlame/receptes#57]
Nincs teljes képernyős előnézet (nálam nagyító jelű gomb) amit arra találtam ki, hogy nagyítva akár laptopon a főzés mellett a konyhába is meg lehessen jeleníteni. Eredetileg akár a konyhabútorba beépített lapos képernyőn megjeleníthetővé akartam tenni.

email: 12.

**Comment by AbstractFlame** [comment]
ez nem a detailWindow??? nem értem, hogy ez mi...

**Comment by samub** [comment]
Layout fullos klsz
Langosítás a statikus elemekre kész
1 maradt: feltölteni adatokkal + esetleg azok langosítása(?)

**Comment by AbstractFlame** [comment]
A comitált verzióban ennek a felülete nincs még készen:
- Nem úgy néz ki, mint az eredetiben
- nem nyúlnak ki (nem nagyítódnak ki) az elemek a képernyű széléig
- a revízió szám kilóg a képernyőből nálam (dolgozzunk mindig némi ráhagyással a GUI-n)

**Comment by samub** [comment]
kész. nem fognak kinyúlni, nála se nyúlnak ki, az eredetiben a layout totálfullpocsék. kész minden csak adatokkal fel kő tölteni
