### ISSUE TITLE
DetailWindow: some modification

### ISSUE THREAD

**Issue by AbstractFlame** [AbstractFlame/receptes#59]
A felirat és a kép is lehetne nagyobb. Ide is kellene teljes képernyős megjelenítés. Ha megtaláltam amit keresek, tehessem ki teljes képernyőre. Okát lásd feljebb.
A léptetésre nem feltétlen kell feliratos gomb, lehetne simán nyilas megoldás. (Mint nálam az adatbázisban.)

email: 14.

**Comment by samub** [comment]
uj detailWindow + az eredetire egy uj gomb ami elohozza az uj detailWindow-t, ami fullscreenes

**Comment by samub** [comment]
+ a mainwindowba is ugyanilyen gomb

**Comment by samub** [comment]
+ mainwindow-ra is "nagyító gomb"
+ gombok grafikásítása

**Comment by AbstractFlame** [comment]
+ "nagyító" button to MainWindow and SearchWindow too
