### ISSUE TITLE
DetailWindow: multilanguaging at combobox doesn't work???

### ISSUE THREAD

**Issue by AbstractFlame** [AbstractFlame/receptes#60]
- Ez kész: Ha nyelvet váltok, akkor a bal felső sarokban is változnia kellene a legördülő menük tartalmának is. Az én tábláim mindenütt tartalmazzák a fordításokat.

- Ugyanez érvényes pl. a mentés feliratra is. L

email: 15.

**Comment by samub** [comment]
Modify/Mentésw multilagosítása
