### ISSUE TITLE
LangSelectWindow revision label from Dictionary doesnt work

### ISSUE THREAD

**Issue by samub** [AbstractFlame/receptes#69]
vmi fura hibat dob ha beirom azt a sort ami langosítaná (line 28)

**Comment by AbstractFlame** [comment]
Azért dob hibát, mert itt még nincs kiválasztva a nyelv. így a translate fv nem tudja lefordítani. Szerintem itt használjuk az angol nevet string literálként beépítve...

**Comment by samub** [comment]
és hogy tom lekérdezni niga ?:DD há nem vagyoknén programozó ee :D

**Comment by AbstractFlame** [comment]
You can query it! Just trust your instincts.
