### ISSUE TITLE
Program Fails sometimes (Memory Leak?) 

### ISSUE THREAD

**Issue by samub** [AbstractFlame/receptes#70]
http://kepfeltoltes.hu/view/160110/programhibaMEmoria_www.kepfeltoltes.hu_.png

**Comment by AbstractFlame** [comment]
Nah ez para... ha ilyen van, akkor légyszi ne nyomj semmit, szólj azonnal és átmegyek a gépedre megnézni. Debugban érdemes használni a progit és akkor még azt is látni fogjuk, hogy honnan jön a hiba
