### ISSUE TITLE
Add new line into history

### ISSUE THREAD

**Issue by AbstractFlame** [AbstractFlame/receptes#82]
1.       A történetet ki kellene még egészíteni. A szövegeket előző levelemben megküldtem, de itt ismét:

 
en          4.00   Converting to executable
de          4.00  Konvertieren in ausführbar
hu          4.00   Futtatható (exe) állománnyá alakítás
sk           4.00   Spustiteľný súbor (EXE) zásoby formácie

email: 1.

**Comment by samub** [comment]
done + added to History WIndow
