### ISSUE TITLE
Fix full screen button on detailWindow

### ISSUE THREAD

**Issue by AbstractFlame** [AbstractFlame/receptes#83]
A teljes képernyős nagyítás nem mindenütt működik.

email: 2.

**Comment by samub** [comment]
és hol nem működik basszameg ?:DDD

**Comment by samub** [comment]
megtaláltam. a FoodDetailsWindow-ban van a kép alatti gomb. csináltam neki eseményt[plusz lemásoltam a többi ilyen gomb logikáját], de nem működött kapcsiból úgy ahogy a többi oldalon és nem volt kedvem éjfélkor felfogni a programodat úgyh leszartam, bocs :D

**Comment by AbstractFlame** [comment]
Megértelek.
