### ISSUE TITLE
Fix "Nagyítás and Fullscreen" doesn't work at SearchWindow

### ISSUE THREAD

**Issue by AbstractFlame** [AbstractFlame/receptes#91]
Keresés külön menűben (ablakban OK, nagyon tetszik !!!) Itt ellenben hiába választok receptet, sem a nagyítás (új ablakban), sem a teljes képernyős megjelenítés nem igazán működik.

új email: 6.

**Comment by samub** [comment]
ezt gecire nem vágom miafasz

**Comment by AbstractFlame** [comment]
Email: Nálunk működik. Megnézné még egyszer?
